[config.wallpaper]
command = "caelestia"
arguments = ["wallpaper", "-f"]
set = false


[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.hamr]
input_path = "~/.config/matugen/templates/hamr-colors.json"
output_path = "~/.config/hamr/colors.json"